/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import entidades.Libro;
import idao.ILibroDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author gaspa
 */
public class DlgLibro extends javax.swing.JDialog {
    private Libro libro;
    private int operacion;
    private StringBuffer respuesta;
    /**
     * Creates new form DlgLibro
     */
    public DlgLibro(java.awt.Frame parent, String title, boolean modal,Libro libro,int operacion, StringBuffer respuesta) {
        super(parent,title, modal);
        this.libro = libro;
        this.operacion = operacion;
        this.respuesta = respuesta; 
        initComponents();
        // Modifica el título del botón botonAceptar y establece si los
        // botones botonRestaurar y botonCancelar estarán habilitados.
        // Si la operación es agregar
        if(operacion == 0)
            botonAceptarLibro.setText("Guardar");
        // Si la operación es actualizar
        else if(operacion == 1)
        botonAceptarLibro.setText("Actualizar");
        // Si la operación es eliminar
        else if(operacion == 2) {
        botonAceptarLibro.setText("Eliminar");
        botonRestaurar.setEnabled(false);
        }
        // Si la operación es desplegar
        else if(operacion == 3) {
        botonAceptarLibro.setText("Continuar");
        botonRestaurar.setEnabled(false);
        botonCancelar.setEnabled(false);
        }

        // Despliega la ISBN 
        campoTextoIsbn.setText(String.valueOf(libro.getId()));

        // Si la operación es de actualizar, eliminar o desplegar,
        if((operacion == 2) ||
        (operacion == 1) ||
        (operacion == 3)) {
        // despliega el resto de los datos del libro
        campoTextoTitulo.setText(libro.getTitulo());
        campoTextoAutor.setText(libro.getAutor());
        }

        // Si la operación es de eliminar o desplegar
        if((operacion == 2) ||
        (operacion == 3)) {
        // hace los campos de texto de sólo lectura
        campoTextoTitulo.setEditable(false);
        campoTextoAutor.setEditable(false);
        }

        // Establece el valor por omisión para respuesta, por si se cierra el
        // cuadro de diálogo presionando el botón cerrar o el botón cancelar
        respuesta.append("Cancelar");
        // centra el cuadro de dialogo sobre la ventana de la aplicación
        

        // Muestra el cuadro de diálogo
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoAutor = new javax.swing.JTextField();
        campoTextoTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonAceptarLibro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRestaurar = new javax.swing.JButton();
        campoTextoIsbn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        campoTextoAutor.setColumns(35);

        campoTextoTitulo.setColumns(35);

        jLabel1.setText("ISBN");

        jLabel2.setText("Titulo");

        botonAceptarLibro.setText("Aceptar");
        botonAceptarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarLibroActionPerformed(evt);
            }
        });

        jLabel3.setText("Autor");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRestaurar.setText("Restaurar");
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });

        campoTextoIsbn.setEditable(false);
        campoTextoIsbn.setColumns(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextoIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(botonAceptarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRestaurar)
                .addGap(147, 147, 147)
                .addComponent(botonCancelar)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoTextoIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoTextoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarLibro)
                    .addComponent(botonCancelar)
                    .addComponent(botonRestaurar))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarLibroActionPerformed
        
        // Si la operación es Agregar o Actualizar
        if((operacion == 0) ||
        (operacion == 1)) {
        // Toma los valores capturados en los campos de texto y almacénalos en 
        //el parámetro libro.

        libro.setTitulo(campoTextoTitulo.getText());
        libro.setAutor(campoTextoAutor.getText());
        }
        // Borra el contenido de respuesta
        respuesta.delete(0, respuesta.length());
        // Establece que se presionó el botón botonAceptar
        respuesta.append("Aceptar");
        // Destruye el cuadro de díalogo
        dispose(); 
        
        
    }//GEN-LAST:event_botonAceptarLibroActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // Destruye el cuadro de díalogo
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        // Restaura el contenido de los campos de texto a su valor original
        // Si la operación es Agregar
        if(operacion == 0) {
            
        campoTextoTitulo.setText("");
        campoTextoAutor.setText("");
        }

        // Si la operación es Actualizar
        if(operacion == 1) {
            
        campoTextoTitulo.setText(libro.getTitulo());
        campoTextoAutor.setText(libro.getAutor());
        }
    }//GEN-LAST:event_botonRestaurarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAceptarLibro;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JTextField campoTextoAutor;
    private javax.swing.JTextField campoTextoIsbn;
    private javax.swing.JTextField campoTextoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
